name: deploy github pages

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
          
      - name: setup sphinx
        run: pip install -U sphinx sphinx-revealjs myst-parser
        
      - name: build slide
        run: cd project && make revealjs && cd -

      - name: setup pages
        uses: actions/configure-pages@v1

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './project/_build/revealjs'

      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@main
